INFO     root:conftest.py:208 === Starting test_negative_sigin_invalid_credentials_500 Test (Negative) ===
INFO     root:conftest.py:209 API Response: 500 | {"ErrorCode":null,"ErrorDescription":null,"ErrorDetail":null,"Url":"http://api.dev.nerdunited.net/api/auth/signin/","type":null,"title":"A problem occurred processing your request","status":null,"detail":"System.Exception: BadRequest: {\n  \u0022error\u0022: {\n    \u0022code\u0022: 400,\n    \u0022message\u0022: \u0022EMAIL_NOT_FOUND\u0022,\n    \u0022errors\u0022: [\n      {\n        \u0022message\u0022: \u0022EMAIL_NOT_FOUND\u0022,\n        \u0022domain\u0022: \u0022global\u0022,\n        \u0022reason\u0022: \u0022invalid\u0022\n      }\n    ]\n  }\n}\n\n   at Nerd.Membership.Core.Authentication.FullAuthenticationService.FirebaseSignIn(String email, String password) in /src/Nerd.Membership/Nerd.Membership.Core/Authentication/FullAuthenticationService.cs:line 67\n   at Nerd.Membership.Core.Authentication.FullAuthenticationService.SignIn(String email, String password, String ipAddress) in /src/Nerd.Membership/Nerd.Membership.Core/Authentication/FullAuthenticationService.cs:line 34\n   at Nerd.Membership.Api.Controllers.V1.FullAuthController.SignIn(SignInRequest request) in /src/Nerd.Membership/Nerd.Membership.Api/Controllers/V1/FullAuthController.cs:line 118\n   at lambda_method1572(Closure , Object )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Awaited|12_0(ControllerActionInvoker invoker, ValueTask\u00601 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Nerd.Common.Logging.NerdApiGlobalLogScopeMiddleware.InvokeAsync(HttpContext httpContext) in /src/Nerd.Common/Logging/NerdApiGlobalLogScopeMiddleware.cs:line 41\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","instance":null}
INFO     root:conftest.py:219 Test 'test_negative_sigin_invalid_credentials_500' (Negative) SUCCESS.
INFO     root:conftest.py:220 === Ending test_negative_sigin_invalid_credentials_500 Test (Negative) ===