INFO     root:conftest.py:208 === Starting test_negative_get_invoice_invalid_id Test (Negative) ===
INFO     root:conftest.py:209 API Response: 400 | {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-4a569d8a5092354fc0807516c223c62f-cc4b3c2b57aebed1-00","errors":{"Id":["'Id' must not be empty."]}}
INFO     root:conftest.py:219 Test 'test_negative_get_invoice_invalid_id' (Negative) SUCCESS.
INFO     root:conftest.py:220 === Ending test_negative_get_invoice_invalid_id Test (Negative) ===